# 파이토치 패키지의 기본 구성
1. `torch`
  - main namespace
  - 포함하는 항목
    - tensor 등의 수학 함수
  - numpy와 유사한 구조를 가집니다.
2. `torch.autograd`
  - 포함하는 항목
    - auto differential을 위한 함수
    - auto differential on/off를 제어하는 context_manager (enable_grad,no_grad)
    - 자체 미분 가능 함수를 정의할 때 사용하는 base class `Function`이 포함되어 있습니다.
3. `torch.nn`
  - 포함하는 항목
    - neural network를 구축하기 위한 다양한 Data Structure, Layer 정의
      - ex) RNN,LSTM,ReLU,MSELoss 등
4. `torch.optim`
  - SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘을 가집니다.
5. `torch.utils.data`
  - SGD의 반복 연산을 실행할 때 사용하는 mini batch용 utility function이 정의되어 있습니다.
6. `torch.onnx`
  - ONNX format으로 model을 export할 때 사용합니다.
    - ONNX는 서로 다른 딥러닝 프레임워크 간에 모델을 공유할 때 사용하는 format

### Pytorch Model을 훈련하기 위해서는 데이터를 Tensor의 형태로 만들어야 합니다.

## Tesnor Manipulation
### Index
- 벡터, 행렬, 그리고 텐서
- Numpy Review
- Pytorch Tensor Allocation
- Matrix Multiplication
- Other Basic Ops

### Vector, Matrix, Tensor
- 3개가 딥러닝의 **기본 단위**입니다.
- vector ( 1-d Tensor )
  - 1차원으로 구성된 값
- Matrix ( 2-d Tensor )
  - 2차원으로 구성된 값
- Tensor ( 3-d Tensor )
  - 3차원으로 구성된 값

### Pytorch Tensor Allocation 실습
1. 1D with PyTorch
2. 2D with Pytorch
3. Broadcasting
4. Matrix Multiplication Vs Multiplication
5. Mean
6. Sum
7. Max, Argmax
8. View
9. Squeeze
10. Unsqueeze
11. Type Casting
12. concatenate
13. Stacking
14. ones_like, zeros_lie
15. Inplace Operation


In [ ]:
# 1-D Tensor
import torch
t = torch.Tensor([0.,1.,2.,3.,4.])
print(t)
print(t.ndim) # dimension
print(t.shape) # shape
print(t.size()) # shape

tensor([0., 1., 2., 3., 4.])
1
torch.Size([5])
torch.Size([5])


In [ ]:
# 2-D Tensor
t2 = torch.Tensor([[1.,2.,3.],
                   [4.,5.,6.],
                   [7.,8.,9.]])
print(t2)
print(t2.ndim)
print(t2.shape)
print(t2.size())

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
2
torch.Size([3, 3])
torch.Size([3, 3])


In [ ]:
# BroadCasting
## 행렬의 크기가 다른 경우 자동으로 크기를 맞춰 수행하는 기능
m1 = torch.Tensor([1,2,3])
m2 = torch.Tensor([4])
m3 = torch.Tensor([5,6])
print(m1+m2)
#print(m1+m3) #모든 경우에 되는 것은 X (둘이 약수 관계여야 합니다.)

tensor([5., 6., 7.])


In [ ]:
# Matrix Multiplication Vs Multiplication
## matmul -> 내적(행렬곱셈) , multiplication -> 원소별 곱셈
m1 = torch.Tensor([[2,3],[4,5]])
m2 = torch.Tensor([10,20])
print(torch.matmul(m1,m2)) # m1 내적 m2
print(m1.matmul(m2)) # m1 내적 m2
print(m2.matmul(m1)) # m2 내적 m1
# 행렬 곱은 순서가 결과에 영향을 미칩니다.
## multiplication -> 원소별 곱셈
print(torch.multiply(m1,m2)) # m1 * m2
print(m1.mul(m2)) # m1 * m2
print(m2.mul(m1)) # m2 * m1

tensor([ 80., 140.])
tensor([ 80., 140.])
tensor([100., 130.])
tensor([[ 20.,  60.],
        [ 40., 100.]])
tensor([[ 20.,  60.],
        [ 40., 100.]])
tensor([[ 20.,  60.],
        [ 40., 100.]])


In [ ]:
# Mean -> 모든 원소 합의 평균

t = torch.Tensor([1,2])
print(t.mean()) # 1-D tensor의 mean
t2 = torch.Tensor([[1,2],[4,5]])
print(t2.mean()) # 2-D tensor의 mean

## 열의 평균을 구하는 방법
print("열의 평균")
print(t2.mean(dim=0)) # dim = 0 을 제거한다는 의미 (dim=0 (행))
## 행의 평균
print("행의 평균")
print(t2.mean(dim=1)) # dim = 1 을 제거한다는 의미 (dim=1 (열))

tensor(1.5000)
tensor(3.)
열의 평균
tensor([2.5000, 3.5000])
행의 평균
tensor([1.5000, 4.5000])


In [ ]:
# Sum -> 원소의 합
print("sum of 1-d array")
print(t.sum())
print("++++++++++++++++")
print("sum of 2-d array")
print(t2.sum())
print("+++++++++++++++")
print("sum of column of 2-d array")
print(t2.sum(dim=0))
print("+++++++++++++++")
print("sum of row of 2-d array")
print(t2.sum(dim=1))


sum of 1-d array
tensor(3.)
++++++++++++++++
sum of 2-d array
tensor(12.)
+++++++++++++++
sum of column of 2-d array
tensor([5., 7.])
+++++++++++++++
sum of row of 2-d array
tensor([3., 9.])


In [ ]:
# Max, ArgMax
## Max -> 원소의 최대값
## Argmax -> 최대값을 가진 Index
print("t2의 Max")
print(t2.max())
print("++++++++++")
print("t2의 Argmax")
print(t2.argmax())
## column,row별 최대값 (dim인자를 이용하게 되면 indice로 argmax까지 자동으로 알려줍니다.)
print("Max value per column of t2")
print(t2.max(dim = 0))
print("Max value per row of t2")
print(t2.max(dim = 1))
print("Argmax per column of t2")
print(t2.argmax(dim = 0))
print("Argmax per row of t2")
print(t2.argmax(dim = 1))

t2의 Max
tensor(5.)
++++++++++
t2의 Argmax
tensor(3)
Max value per column of t2
torch.return_types.max(
values=tensor([4., 5.]),
indices=tensor([1, 1]))
Max value per row of t2
torch.return_types.max(
values=tensor([2., 5.]),
indices=tensor([1, 1]))
Argmax per column of t2
tensor([1, 1])
Argmax per row of t2
tensor([1, 1])


In [ ]:
# View
## numpy의 reshape역할
import numpy as np
t = torch.Tensor(np.arange(16)) # 16,1 크기의 tensor 생성
## 현재 Tensor size 확인
print("변경 전 Tensor size")
print(t.size())
print("+++++++++++++")
## view를 이용하여 4,2,2로 변경
t_ver2 = t.view(4,2,2)
## 변경 뒤 Tensor size 확인
print("3차원 변경 후 Tensor size")
print(t_ver2.size())
print("+++++++++++++")
## view -1 기능 이용
### view에서 -1은 사용자가 설정하지 않고 남은 몫을 넣도록 하는 의미입니다. (ex, 6x3 을 view(-1,6)이라고 하면 18(3x6)을 6으로 나눈 몫 3이 -1로 들어갑니다. )
t_ver3 = t.view(-1,4)
print("-1을 이용하여 2차원으로 변경 후 Tensor size")
print(t_ver3.size())
print("++++++++++++++")

변경 전 Tensor size
torch.Size([16])
+++++++++++++
3차원 변경 후 Tensor size
torch.Size([4, 2, 2])
+++++++++++++
-1을 이용하여 2차원으로 변경 후 Tensor size
torch.Size([4, 4])
++++++++++++++


In [ ]:
# Squeeze
## 차원이 1인 경우 1인 차원을 제거하는 기능
t = torch.Tensor([[1],[2],[3]])
print("Tensor t")
print(t)
print("+++++++++++++++")
print("t size")
print(t.size()) # size 확인
print("+++++++++++++++")
print("squeeze")
print(t.squeeze()) # 1인 차원을 제거
print("+++++++++++++++")
print("1인 차원 제거 후의 t shape")
print(t.squeeze().shape) # 1이었던 두 번째 차원이 제거

Tensor t
tensor([[1.],
        [2.],
        [3.]])
+++++++++++++++
t size
torch.Size([3, 1])
+++++++++++++++
squeeze
tensor([1., 2., 3.])
+++++++++++++++
1인 차원 제거 후의 t shape
torch.Size([3])


In [ ]:
# Unsqueeze
t = torch.Tensor([[1],[2],[3]])
print("Tensor t")
print(t)
print("+++++++++++++++")
print("t size")
print(t.size()) # size 확인
print("+++++++++++++++")
print("unsqueeze")
print(t.unsqueeze(0)) # 1인 차원을 제거
print("+++++++++++++++")
print("맨 앞에 새로운 차원 추가 후의 t shape")
print(t.unsqueeze(0).shape) # 1이었던 두 번째 차원이 제거

Tensor t
tensor([[1.],
        [2.],
        [3.]])
+++++++++++++++
t size
torch.Size([3, 1])
+++++++++++++++
unsqueeze
tensor([[[1.],
         [2.],
         [3.]]])
+++++++++++++++
맨 앞에 새로운 차원 추가 후의 t shape
torch.Size([1, 3, 1])


In [ ]:
# TypeCasting
## 자료형을 변환하는 기능
### long type tensor 선언
lt = torch.LongTensor([1,2,3,4])
print("long tensor")
print(lt.dtype)
print("++++++++++++")
### long -> float 변경
ft = lt.float()
print("float tensor")
print(ft.dtype)
print("++++++++++++")
### Byte Type tensor 선언
bt = torch.ByteTensor([True,False,True,False])
print("byte tensor")
print(bt.dtype)
print("++++++++++++")
### byte -> long, float 변경
bt_to_lt = bt.long()
bt_to_ft = bt.float()
print("bt -> lt")
print(bt_to_lt.dtype)
print("++++++++++++")
print("bt -> ft")
print(bt_to_ft.dtype)
print("++++++++++++")

long tensor
torch.int64
++++++++++++
float tensor
torch.float32
++++++++++++
byte tensor
torch.uint8
++++++++++++
bt -> lt
torch.int64
++++++++++++
bt -> ft
torch.float32
++++++++++++


In [ ]:
# Concatenate
## Tensor를 연결하는 것
x1 = torch.Tensor([[1,2],[3,4]])
x2 = torch.Tensor([[5,6],[7,8]])
## Tensor를 첫 번째 차원으로 연결
print("첫 번째 차원(행)으로 연결 (행의 개수 증가)")
concat_dim1= torch.cat([x1,x2],dim=0)
print(concat_dim1)
## Tensor를 두 번째 차원으로 연결
print("두 번째 차원(열)으로 연결 (열의 개수 증가)")
concat_dim2= torch.cat([x1,x2],dim=1)
print(concat_dim2)

첫 번째 차원(행)으로 연결 (행의 개수 증가)
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
두 번째 차원(열)으로 연결 (열의 개수 증가)
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [ ]:
# Stacking
## concat과 다른 연결 방식
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])
## Tensor를 stack으로 연결
print("x,y,z stack")
print(torch.stack([x,y,z]))
print("#############")
## stack은 각 Tensor의 0번째 차원을 추가하여 0번째 차원을 이어 붙인 것과 같습니다. 즉 아래 코드와 동일합니다.
print("concatenate로 구현한 stack")
print("각 tensor에 차원 추가 및 추가한 차원으로 연결")
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))
print("#############")
## dim을 추가한 stack방식
print("stack dim = 1")
print(torch.stack([x,y,z],dim = 1))
# 이것은 마찬가지로 각 텐서에 unsqueeze(1)로 1차원을 추가하고, 해당 차원으로 연결하는 것과 같습니다.

x,y,z stack
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
#############
concatenate로 구현한 stack
각 tensor에 차원 추가 및 추가한 차원으로 연결
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
#############
stack dim = 1
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
# ones_like, zeros_like
## ones_like, zeros_like은 제공한 Tensor와 동일한 shape을 가지고 1 또는 0으로 채워진 tensor를 반환합니다.
x = torch.FloatTensor([[1,2,3],[9,8,7]])
print("x")
print(x)
print("#############")
print("ones_like(x)")
print(torch.ones_like(x))
print("#############")
print("zeros_like(x)")
print(torch.zeros_like(x))
print("#############")

x
tensor([[1., 2., 3.],
        [9., 8., 7.]])
#############
ones_like(x)
tensor([[1., 1., 1.],
        [1., 1., 1.]])
#############
zeros_like(x)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
#############


In [ ]:
# Inplace Operation
## inplace operation은 계산 결과가 기존 변수에 반영되는 operation(연산)을 말합니다.
print("Not Inplace Operation")
print(x.add(3))
print("X after operation")
print(x)
print("반영되지 않습니다.")
print("###################")
print("Inplace Operation (adding _ to tail of operation)")
print(x.add_(3))
print("X after operation")
print(x)
print("반영이 되었습니다.")

Not Inplace Operation
tensor([[ 4.,  5.,  6.],
        [12., 11., 10.]])
X after operation
tensor([[1., 2., 3.],
        [9., 8., 7.]])
반영되지 않습니다.
###################
Inplace Operation (adding _ to tail of operation)
tensor([[ 4.,  5.,  6.],
        [12., 11., 10.]])
X after operation
tensor([[ 4.,  5.,  6.],
        [12., 11., 10.]])
반영이 되었습니다.
