# 모델 만들기
- 순서
  1. 데이터 이해
    - 학습할 데이터를 확인하고 이해합니다.
    - Input, Output Data를 각각 다른 Tensor에 저장합니다.
  2. 가설 수립
    - ML에서 식을 세울 때 식을 **가설**이라고 합니다.
    - 가설은 임의로 추측하여 세워보는 식일 수도 있고, 경험적으로 알고 있는 식일 수도 있습니다.
  3. 손실 계산
    - cost function, loss function, error function, objective function 모두 같은 의미의 용어입니다.
    - 실제 값과 예측 값의 차이를 통해 모델이 잘 예측하는지 확인하기 위한 과정입니다.
  4. optimizer - 경사 하강법
    - cost function의 값을 최소로 하기 위해 사용되는 알고리즘 ( optimizer 알고리즘 )
    - optimizer는 cost function의 결과를 W로 미분하여 구한 기울기에 특정 숫자(학습률)를 곱한 값을 빼서 새로운 W로 사용하는 식으로 이용됩니다.
  - 문제에 따라 적절한 hypothesis, cost function, optimizer는 모두 다릅니다.
  


# Implementing Linear Regression using Pytorch

- setting (import)
- variable allocation
- initialize weight and bias
- establish hypothesis
- declare cost function
- implementing gradient descent
- full code

In [2]:
# setting import
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np

torch.manual_seed(42) # for reproducibility of model

In [6]:
# variable allocation
x_train = torch.FloatTensor(np.arange(10))
y_train = torch.FloatTensor(np.arange(0,30,3))
print(x_train) #값 확인
print(x_train.shape) #size확인
print(y_train)
print(y_train.shape)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([10])
tensor([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])
torch.Size([10])


In [7]:
# initial weight and bias
W = torch.zeros(1,requires_grad=True) # requires_grad를 True함으로서 torch가 이 tensor에 대한 연산을 추적하게 합니다.
b = torch.zeros(1, requires_grad=True)
print("W =",W)
print("b =",b)
# 현재 식 y = 0x+0

W = tensor([0.], requires_grad=True)
b = tensor([0.], requires_grad=True)


In [8]:
# establish hypothesis
hypo = x_train*W+b # linear regression 이므로 y = Wx+b 형태
print(hypo)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], grad_fn=<AddBackward0>)


In [9]:
# declare cost function
cost = torch.mean((hypo-y_train)**2) # MSE 구현
print(cost)

tensor(256.5000, grad_fn=<MeanBackward0>)


In [12]:
# implementing gradient descent

optimizer = optim.SGD([W,b],lr = 0.01) # pytorch optim SGD를 사용합니다. 이때 학습 대상(W,b)를 인자로 전달해주고, learning rate는 0.01로 설정합니다.

In [13]:
# how to using optimizer
optimizer.zero_grad # gradient initialize
cost.backward() #W,b 에 대한 gradinet 계산
optimizer.step() # W,b update

In [25]:
X_train = torch.FloatTensor([1,2,3])
Y_train = torch.FloatTensor([4,5,6])

W = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True)

optimizer = optim.SGD([W,b],lr=0.01)

epochs = 1000
for epoch in range(1,epochs+1):
  output = X_train*W + b
  loss = torch.mean((Y_train-output)**2)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  if epoch%100 == 0:
    print(f"epoch {epoch}/{epochs} \| W : {W} b : {b} grad : {W.grad}") # grad가 점점 줄어드는 것을 확인할 수 있습니다.

epoch 100/1000 \| W : tensor([1.7417], requires_grad=True) b : tensor([1.3138], requires_grad=True) grad : tensor([0.1786])
epoch 200/1000 \| W : tensor([1.5831], requires_grad=True) b : tensor([1.6745], requires_grad=True) grad : tensor([0.1405])
epoch 300/1000 \| W : tensor([1.4584], requires_grad=True) b : tensor([1.9580], requires_grad=True) grad : tensor([0.1105])
epoch 400/1000 \| W : tensor([1.3603], requires_grad=True) b : tensor([2.1809], requires_grad=True) grad : tensor([0.0868])
epoch 500/1000 \| W : tensor([1.2832], requires_grad=True) b : tensor([2.3561], requires_grad=True) grad : tensor([0.0682])
epoch 600/1000 \| W : tensor([1.2226], requires_grad=True) b : tensor([2.4939], requires_grad=True) grad : tensor([0.0537])
epoch 700/1000 \| W : tensor([1.1750], requires_grad=True) b : tensor([2.6021], requires_grad=True) grad : tensor([0.0422])
epoch 800/1000 \| W : tensor([1.1376], requires_grad=True) b : tensor([2.6872], requires_grad=True) grad : tensor([0.0332])
epoch 90

In [26]:
# zero_grad를 하지 않는다면?
X_train = torch.FloatTensor([1,2,3])
Y_train = torch.FloatTensor([4,5,6])

W = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True)

optimizer = optim.SGD([W,b],lr=0.01)

epochs = 1000
for epoch in range(1,epochs+1):
  output = X_train*W + b
  loss = torch.mean((Y_train-output)**2)
  #optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  if epoch%100 == 0:
    print(f"epoch {epoch}/{epochs} \| W : {W} b : {b} grad : {W.grad}") # grad가 점점 줄어드는 것을 확인할 수 있습니다.

epoch 100/1000 \| W : tensor([2.3831], requires_grad=True) b : tensor([3.0605], requires_grad=True) grad : tensor([-62.9186])
epoch 200/1000 \| W : tensor([0.9958], requires_grad=True) b : tensor([5.3501], requires_grad=True) grad : tensor([51.6932])
epoch 300/1000 \| W : tensor([-1.5019], requires_grad=True) b : tensor([3.3407], requires_grad=True) grad : tensor([13.3790])
epoch 400/1000 \| W : tensor([2.6057], requires_grad=True) b : tensor([1.9019], requires_grad=True) grad : tensor([-58.9015])
epoch 500/1000 \| W : tensor([2.8937], requires_grad=True) b : tensor([1.7063], requires_grad=True) grad : tensor([44.6695])
epoch 600/1000 \| W : tensor([-1.3236], requires_grad=True) b : tensor([2.9744], requires_grad=True) grad : tensor([14.5651])
epoch 700/1000 \| W : tensor([0.7569], requires_grad=True) b : tensor([5.3984], requires_grad=True) grad : tensor([-63.4597])
epoch 800/1000 \| W : tensor([2.3503], requires_grad=True) b : tensor([3.5491], requires_grad=True) grad : tensor([44.89