# nn.Module과 클래스로 구현
- [3-1](https://colab.research.google.com/drive/1fLFUt0L3Ydm2G_wrP3F00E9jLpOvdxig?usp=drive_link), [3-2](https://colab.research.google.com/drive/1bV6Hu17QyJ9I-NkzentlXBunJR9iwk4Y?usp=drive_link)에서는 loss, hypothesis를 직접 정의하여 사용했습니다.
- 이번 단계에서는 pytorch에 구현되어 있는 것을 이용하여 구현합니다.

In [5]:
# setting
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(42)

### simple linear regression

In [9]:
# simple linear regression
x_train = torch.Tensor([[1],[2],[3],[4],[5]])
y_train = torch.Tensor([[6],[7],[8],[9],[10]])

model = nn.Linear(1,1) # 모델 simple linear regression이기 때문에 input_dim = 1 ,output_dim = 1 입니다.
print("model이 가진 parameter :",list(model.parameters())) # W와 b가 저장되어 있습니다.
# parameters에 W랑 b가 저장되어 있으므로 parameters를 전달해줍니다.
opt = optim.SGD(model.parameters(),lr=0.01)

epochs = 2000
for epoch in range(1,epochs+1):
  output = model(x_train)
  loss = F.mse_loss(y_train,output)
  opt.zero_grad()
  loss.backward()
  opt.step()
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, loss.item()))

model이 가진 parameter : [Parameter containing:
tensor([[-0.4869]], requires_grad=True), Parameter containing:
tensor([0.5873], requires_grad=True)]
Epoch  100/2000 Cost: 1.285276
Epoch  200/2000 Cost: 0.652878
Epoch  300/2000 Cost: 0.331641
Epoch  400/2000 Cost: 0.168463
Epoch  500/2000 Cost: 0.085574
Epoch  600/2000 Cost: 0.043469
Epoch  700/2000 Cost: 0.022081
Epoch  800/2000 Cost: 0.011216
Epoch  900/2000 Cost: 0.005698
Epoch 1000/2000 Cost: 0.002894
Epoch 1100/2000 Cost: 0.001470
Epoch 1200/2000 Cost: 0.000747
Epoch 1300/2000 Cost: 0.000379
Epoch 1400/2000 Cost: 0.000193
Epoch 1500/2000 Cost: 0.000098
Epoch 1600/2000 Cost: 0.000050
Epoch 1700/2000 Cost: 0.000025
Epoch 1800/2000 Cost: 0.000013
Epoch 1900/2000 Cost: 0.000007
Epoch 2000/2000 Cost: 0.000003


### multivariance linear regression

In [17]:
X_train = torch.Tensor(
    [[1,2,3,4,5],
    [1,3,5,7,9],
    [1,7,3,6,10]]
)
Y_train = torch.Tensor(
    [[15],
    [25],
    [27]]
)

W = torch.zeros((5,1),requires_grad=True)
b = torch.zeros(1,requires_grad=True)

model = nn.Linear(5,1)

opt = optim.SGD(model.parameters(),lr = 0.001)

epochs = 2400
for epoch in range(epochs):
  output = model(X_train)
  loss = F.mse_loss(Y_train,output)

  opt.zero_grad()
  loss.backward()
  opt.step()
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, loss.item()))
with torch.no_grad() :
  test = torch.Tensor([[1,2,3,8,3]])
  pred = model(test)
  print(f"{test} 예측 결과",pred)


Epoch    0/2400 Cost: 420.860931
Epoch  100/2400 Cost: 0.114125
Epoch  200/2400 Cost: 0.076091
Epoch  300/2400 Cost: 0.065732
Epoch  400/2400 Cost: 0.061275
Epoch  500/2400 Cost: 0.058158
Epoch  600/2400 Cost: 0.055421
Epoch  700/2400 Cost: 0.052861
Epoch  800/2400 Cost: 0.050428
Epoch  900/2400 Cost: 0.048109
Epoch 1000/2400 Cost: 0.045898
Epoch 1100/2400 Cost: 0.043788
Epoch 1200/2400 Cost: 0.041775
Epoch 1300/2400 Cost: 0.039855
Epoch 1400/2400 Cost: 0.038023
Epoch 1500/2400 Cost: 0.036275
Epoch 1600/2400 Cost: 0.034607
Epoch 1700/2400 Cost: 0.033017
Epoch 1800/2400 Cost: 0.031499
Epoch 1900/2400 Cost: 0.030051
Epoch 2000/2400 Cost: 0.028670
Epoch 2100/2400 Cost: 0.027352
Epoch 2200/2400 Cost: 0.026095
Epoch 2300/2400 Cost: 0.024895
tensor([[1., 2., 3., 8., 3.]]) 예측 결과 tensor([[15.4467]])
