In [1]:
import numpy as np
import torch
import torch.nn as nn

## Vector
- 크기와 방향을 가진 양
- 숫자가 나열된 형상으로 1차원 리스트로 표현

## Matrix
- Row,Column을 가지는 2차원 형상을 갖는 구조

## Tensor
- Row,Column,Channel 이상을 가지는 3차원 이상의 형상을 갖는 구조

### NLP에서 3D Tensor를 자주 사용하는 이유

- 자연어 처리에서 3차원은 (sample, timesteps, word_dim) 또는 (batch_size, timesteps, word_dim)으로 구성됩니다.
  - sample, batch_size -> 샘플의 개수 (batch_size는 batch로 나누어 훈련할 때 사용됩니다. 나누지 않는 경우에는 sample이 적용됩니다.)
  - timesteps -> sequence의 길이
  - word_dim -> 단어를 표현하는 벡터의 차원

- 예를 들어, I like a pizza 라는 단어를 One-hot encoding을 활용하여 Embedding 한다고 가정하면, 아래와 같이 표현될 수 있습니다.
  - I > [ 1 ,0 ,0, 0, 0, 0 ]
  - like > [ 0, 1, 0, 0, 0, 0 ]
  - a > [ 0, 0, 1, 0, 0, 0 ]
  - pizza > [ 0, 0, 0, 1, 0, 0 ]
  - 따라서 **한 단어**를 표현하기 위해서는 **1차원(Vector)**가 필요하고,
  - **한 문장**을 표현하기 위해서는 단어들이 연결된 **2차원(Matrix)**이 필요하고,
  - **여러 문장**을 표현한다면 이것을 한 번 더 묶어야하므로, **3차원(Tensor)**이 필요합니다.



In [2]:
## 0차원 텐서 (스칼라)
d = np.array(5)
print(d.ndim) #np.array(5)의 차원 (축의 개수)
print(d.shape) #np.array(5)의 shape

0
()


In [3]:
## 1차원 텐서 (벡터)
d = np.array([1,2,3,4])
print(d.ndim) #np.array([1,2,3,4])의 차원 (축의 개수)
print(d.shape) #np.array(5)의 shape

1
(4,)


In [4]:
## 2차원 텐서 (행렬)
d = np.array([[1,2],[3,4]])
print(d.ndim)
print(d.shape)

2
(2, 2)


In [7]:
## 3차원 텐서(텐서)
d = np.array([ [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]], [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]] ])
print(d.ndim)
print(d.shape)

3
(2, 3, 5)


'\n자연어 처리에서 가장 자주 쓰는 형태\n자연어 처리에서 3차원은 (sample, timesteps, word_dim) 또는 (batch_size, timesteps, word_dim)으로 구성됩니다.\n\nsample, batch_size -> 샘플의 개수 (batch_size는 batch로 나누어 훈련할 때 사용됩니다. 나누지 않는 경우에는 sample이 적용됩니다.)\ntimesteps -> sequence의 길이\nword_dim -> 단어를 표현하는 벡터의 차원\n'

## Vector와 Matrix의 연산
- 벡터 행렬의 덧셈 뺄셈
  - 같은 위치의 요소별로 계산이 됩니다.
    - 이것을 전문적으로 element-wise 연산이라고 합니다.
- 벡터 내적, 행렬의 곱셈
  - 점곱, 내적
    - ⋅ 으로 표현
    - 내적이 성립하기 위해서는 Row Vector와 Column Vector의 차원이 같아야하고, 연산자 앞의 벡터가 Row Vector 뒤의 벡터가 Column Vector여야 합니다.
    - 벡터 내적의 결과는 항상 Scalar입니다.
  - 행렬의 곱셈
    - 행렬의 곱셈은 **연산자 앞의 행렬의 행벡터**와 **연산자 뒤의 행렬의 열벡터**가 **내적한 결과**가 원소가 되는 것으로 이루어집니다.
    - 행렬의 곱셈을 하기 위한 조건
      1. 앞의 행렬의 열의 개수와 뒤의 행렬의 행의 개수가 일치해야합니다.
        - A : (3,4) B : (5,3) -> X 불가 4 != 5
        - A : (3,5) B : (5,3) -> O 가능 5 == 5
      2. 두 행렬의 곱으로 나온 결과는 앞의 행렬의 행의 개수와 뒤의 행렬의 열의 개수의 크기를 가집니다.
        - A : (3,5) B : (5,3) -> 결과 C : (3,3)



In [8]:
## 벡터 행렬의 덧셈
A = np.array([1,2,3,4,5])
B = np.array([10,11,12,13,14])
print("A")
print(A)
print("B")
print(B)
print("A+B 덧셈 결과")
print(A+B)

A
[1 2 3 4 5]
B
[10 11 12 13 14]
A+B 덧셈 결과
[11 13 15 17 19]


In [11]:
## 벡터의 내적
A = np.array([1,2,3,4,5])
B = np.array([1,2,3,4,5])
print("A")
print(A)
print("B")
print(B)
print("A와 B의 내적 결과")
print(A.dot(B))

A
[1 2 3 4 5]
B
[1 2 3 4 5]
A와 B의 내적 결과
55


In [17]:
## 행렬의 곱
A = np.array([[1,2,3,],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
B = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("A")
print(A)
print("A.shape : ",A.shape)
print("B")
print(B)
print("B.shape : ",B.shape)
print(np.matmul(A,B))

A
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
A.shape :  (5, 3)
B
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
B.shape :  (3, 5)
[[ 46  52  58  64  70]
 [100 115 130 145 160]
 [154 178 202 226 250]
 [208 241 274 307 340]
 [262 304 346 388 430]]


## Sample과 Feature
- Matrix를 Input으로 입력받는다고 가정할 때,
  - Row -> Sample
  - Column -> Feature